language: ruby
rvm:
  - 2.6.3

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false
  
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site


## Create release in GitHub
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
