title: AEM.Design
name: AEM.Design
email: devops@aem.design
description: > # this means to ignore newlines until next attribute
  Create consistency in your AEM implementations by providing your team with AEM language they can use to describe things they want to achieve.
github_username:  aem-design
